name: "Build and Report Generation"

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: ${{ matrix.java }}
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Build with Gradle
        run: ./gradlew build
  report-generation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Use Java 11
        uses: actions/setup-java@v3
        with:
          distribution: corretto
          java-version: 11
      - run: ./gradlew koverXmlReport
      - name: Upload Ion Schema Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: ion-schema/build/reports/kover/report.xml
      - name: Upload CLI Code Coverage
        uses: codecov/codecov-action@v3
        with:
          file: cli/build/reports/kover/report.xml
